### ISSUE TITLE
Cannot read property 'Message' of null error from init

### ISSUE THREAD

**Issue by pawarvijay** [OpenApi-5p/5paisa-js#12]
**Below is my configuration**

used keys from https://invest.5paisa.com/DeveloperAPI/APIKeys

```
const conf = {
    "appSource": "WEB",
    "appName": "ABC",
    "userId": "userid",
    "password": "password",
    "userKey": "email encrypted key",
    "encryptionKey": "encyption key"
}

const { FivePaisaClient } = require("5paisajs")

var client = new FivePaisaClient(conf)

client.login("email", "password", "dob").then((response) => {
    client.init(response).then(() => {
        console.log('success')
    })
}).catch((err) =>{
    console.log(err)
})
```
**Getting below error**
```
TypeError: Cannot read property 'Message' of null
    at /home/rocket/fireworks/5paisaApi/node_modules/5paisajs/index.js:107:30
    at new Promise (<anonymous>)
    at FivePaisaClient.init (/home/rocket/fireworks/5paisaApi/node_modules/5paisajs/index.js:104:19)
    at execute (/home/rocket/fireworks/5paisaApi/app.js:20:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**on debugging below 5paisajs library code**
```
  this.init = function (response) {
    var promise = new Promise(function (resolve, reject) {
      if (response.data.body.Message == "") {
        console.log(GREEN, `Logged in`);
        CLIENT_CODE = response.data.body.ClientCode;
        resolve();
      } else {
        console.log(RED, response.data.body.Message);
        reject(response.data.body.Message);
      }
    });

    return promise;
  };
```

 **i found below actual error**

![Screenshot from 2021-05-12 22-17-03](https://user-images.githubusercontent.com/5990947/118015292-be480780-b371-11eb-911f-875a5a56a20c.png)

i dont know what parameters are invalid

Thanks for help in advance

**Comment by vaishalijasoliya** [comment]
@5paisa is there any update ?
