### ISSUE TITLE
Getting 400 Bad Request on login

### ISSUE THREAD

**Issue by rahulnlb1** [OpenApi-5p/5paisa-js#27]
I am using the below code to login using the credentials, but getting 400 Bad Request.

```
const conf = {
   * "appSource": "",
   * "appName": "",
   * "userId": "",
   * "password": "",
   * "userKey": "",
   * "encryptionKey": ""
   * }
   * const { FivePaisaClient} = require("5paisajs")
   *
   * var client = new FivePaisaClient(conf)
   *
   * // This client object can be used to login multiple users.
   * client.login("random_email@xyz.com", "password", "YYYYMMDD").then((response) => {
   *     console.log(response);
   * }).catch((err) =>{
   *     // Oh no :/
   *     console.log(err)
   * })
   ```
   
   Please help me resolve the issue.

**Comment by rahulnlb1** [comment]
Error log: 
```
Error: Request failed with status code 400
    at createError (/Users/rahuljain/PersonalProject/trading-5paisa/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/rahuljain/PersonalProject/trading-5paisa/node_modules/axios/lib/core/settle.js:17:12)
    at /Users/rahuljain/PersonalProject/trading-5paisa/node_modules/axios-cookiejar-support/lib/interceptors/response.js:83:25
    at new Promise (<anonymous>)
    at responseInterceptor (/Users/rahuljain/PersonalProject/trading-5paisa/node_modules/axios-cookiejar-support/lib/interceptors/response.js:82:9)
    at /Users/rahuljain/PersonalProject/trading-5paisa/node_modules/axios-cookiejar-support/lib/index.js:130:67
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    ```

**Comment by sbanerjee302** [comment]
@ba11b0y @5paisa is this repository being monitored or maintained in any way ? There seems to be no updates to any of the issues.

**Comment by vaishalijasoliya** [comment]
@5paisa i m facing same issue anyone can help me ?
@ba11b0y @rahulnlb1 @sbanerjee302
